#pragma once
// Main Dialog
#define IDD_MAIN_DIALOG                 1000
#define IDI_MAIN_ICON                   1001
#define IDC_PACKET_LOG_LIST             1002
#define IDC_DATA_DETAIL_EDIT			1003
#define IDC_PATCH_BUTTON                1004
#define IDC_EDIT_BUTTON                 1005
#define IDC_ClEAR_BUTTON                1006
#define IDC_PID_EDIT                    1007
#define IDC_IS_INPACKET_CHECK           1008
#define IDC_MAIN_SEND_BUTTON            1009
// Setting Dialog
#define IDD_SETTING_DIALOG              1100
#define IDC_SETTING_MFCPROPERTYGRID     1101
#define IDC_SAVE_SETTING_BUTTON         1102
#define IDC_RESET_SETTING_BUTTON        1103
// Search Dialog
#define IDD_SEARCH_DIALOG               1200
#define IDC_SEARCH_CONDITION_COMBO      1201
#define IDC_SEARCH_PROCESS_ID_EDIT		1202
#define IDC_SEARCH_TEXT_EDIT			1203
#define IDC_FIND_BUTTON					1204
#define IDC_PACKET_LOG_SEARCH_LIST      1205
// Jump Dialog
#define IDD_JUMP_DIALOG					1300
#define IDC_JUMP_ID_STATIC              1301
#define IDC_JUMP_ID_EDIT                1302
#define IDC_JUMP_BUTTON					1303
// Patch Dialog
#define IDD_PATCH_DIALOG                1400
#define IDC_PROCESS_ID_STATIC           1401
#define IDC_PROCESS_ID_EDIT             1402
#define IDC_INJECT_DLL_BUTTON           1403
// Format Dialog
#define IDD_FORMAT_DIALOG               1500
#define IDC_PACKET_FORMAT_GRID          1501
#define IDC_GEN_CODE_BUTTON             1502
#define IDC_FORMAT_SEND_BUTTON          1503
// GenCode Dialog
#define IDD_GEN_CODE_DIALOG             1600
#define IDC_GEN_CODE_EDIT				1601
// Menu
#define IDM_IMPORT_MENU                 2000
#define IDM_EXPORT_MENU				    2001
#define IDM_SETTING_MENU                2002
#define IDM_SEARCH_MENU					2003
#define IDM_JUMP_MENU					2004
